name: Frontend Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Definir diretório de trabalho correto
        run: 'echo "Diretório atual: $(pwd)"'

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Versão LTS compatível com Angular 19

      - name: Instalar dependências
        working-directory: SitePortifolio2025
        run: npm install

      - name: Build do Angular (modo produção)
        working-directory: SitePortifolio2025
        run: npm run build -- --configuration production

      - name: Deploy para AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: site-portifolio-proj-2025/SitePortifolio2025/dist/site-portfolio2025
